[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "minirst"
author = "Matthias Bussonnier"
author-email = "bussonniermatthias@gmail.com"
home-page = "https://github.com/Carreau/minirst"
classifiers = ["License :: OSI Approved :: MIT License"]

[tool.flit.scripts]
frappuccino = "minirst:main"
